services:
  backend:
    build: .
    container_name: application-container
    ports:
      - "5000:5000"
  postgres:
    image: postgres:18-bookworm
    container_name: database-container
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
